<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MonoBall.Build</RootNamespace>
    <LangVersion>default</LangVersion>
    <RunWorkingDirectory>$(MSBuildProjectDirectory)</RunWorkingDirectory>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Cake.Frosting" Version="6.0.0" />
    <PackageReference Include="Cake.Common" Version="6.0.0" />
  </ItemGroup>
</Project>
