using System.Text.Json;
using Porycon3.Services.Extraction;

namespace Porycon3.Services;

/// <summary>
/// Extracts behavior definitions that match the behavior IDs generated by MapConversionService.TransformBehaviorId().
/// Creates simplified behavior categories (wander, stationary, walk, etc.) rather than one-per-movement-type.
/// </summary>
public class BehaviorExtractor : ExtractorBase
{
    public override string Name => "Behavior Definitions";
    public override string Description => "Extracts NPC behavior definitions and scripts";

    /// <summary>
    /// Core behavior definitions that match the categories used by TransformBehaviorId().
    /// Parameters match what BuildBehaviorParameters() actually generates from map data.
    /// </summary>
    private static readonly List<BehaviorInfo> CoreBehaviors = new()
    {
        // Wander - uses rangeX/rangeY from map data
        new("wander", "Wander", "NPC wanders randomly within a defined range",
            new[] { ("rangeX", "int", (object)0, "Horizontal wander range in tiles"), ("rangeY", "int", (object)0, "Vertical wander range in tiles") }),

        // Stationary - no parameters extracted from map data
        new("stationary", "Stationary", "NPC stays in place, may look around or change facing direction", null),

        // Walk - uses rangeX/rangeY from map data
        new("walk", "Walk", "NPC walks in a pattern or direction",
            new[] { ("rangeX", "int", (object)0, "Horizontal walk range"), ("rangeY", "int", (object)0, "Vertical walk range") }),

        // Jog - no parameters extracted from map data
        new("jog", "Jog", "NPC jogs or runs in place or pattern", null),

        // Follow - no parameters extracted from map data
        new("follow", "Follow", "NPC follows the player or copies player movement", null),

        // Patrol - uses waypoints array from walk_sequence_* movement types
        new("patrol", "Patrol", "NPC follows a defined patrol route with waypoints",
            new[] { ("waypoints", "array", (object)new object[0], "Array of waypoint positions [{x, y}, ...]") }),

        new("invisible", "Invisible", "NPC is invisible and does not interact", null),

        new("buried", "Buried", "NPC is hidden underground (e.g., Diglett encounters)", null),

        new("disguise_tree", "Disguise (Tree)", "NPC disguised as a tree (e.g., Sudowoodo)", null),

        new("disguise_rock", "Disguise (Rock)", "NPC disguised as a rock or mountain (e.g., Kecleon)", null),
    };

    public BehaviorExtractor(string inputPath, string outputPath, bool verbose = false)
        : base(inputPath, outputPath, verbose)
    {
    }

    protected override int ExecuteExtraction()
    {
        // Only generate script definitions - maps reference these directly
        // Layout matches interactions: Scripts/Movement/NPCs/
        var scriptsPath = Path.Combine(OutputPath, "Definitions", "Scripts", "Movement", "NPCs");
        EnsureDirectory(scriptsPath);

        int count = 0;

        WithProgress("Extracting behavior definitions", CoreBehaviors, (behavior, task) =>
        {
            SetTaskDescription(task, $"[cyan]Creating[/] [yellow]{behavior.Name}[/]");

            var scriptDef = CreateScriptDefinition(behavior);
            var fileName = $"{behavior.Id}.json";
            var filePath = Path.Combine(scriptsPath, fileName);
            File.WriteAllText(filePath, JsonSerializer.Serialize(scriptDef, JsonOptions.Default));
            count++;

            LogVerbose($"Created behavior script: {behavior.Name}");
        });

        return count;
    }

    private object CreateScriptDefinition(BehaviorInfo behavior)
    {
        var parameters = new List<object>();

        if (behavior.Parameters != null)
        {
            foreach (var (name, type, defaultValue, desc) in behavior.Parameters)
            {
                parameters.Add(new Dictionary<string, object>
                {
                    ["name"] = name,
                    ["type"] = type,
                    ["defaultValue"] = defaultValue,
                    ["description"] = desc
                });
            }
        }

        return new Dictionary<string, object>
        {
            ["id"] = $"{IdTransformer.Namespace}:script:movement/npcs/{behavior.Id}",
            ["name"] = $"{behavior.Name} Movement Script",
            ["description"] = behavior.Description,
            ["scriptPath"] = $"Scripts/Movement/NPCs/{behavior.Id}.csx",
            ["category"] = "movement",
            ["priority"] = 500,
            ["parameters"] = parameters
        };
    }

    private record BehaviorInfo(
        string Id,
        string Name,
        string Description,
        (string Name, string Type, object Default, string Description)[]? Parameters
    );
}
