using System.Text.Json;

namespace Porycon3.Services;

/// <summary>
/// Extracts behavior definitions that match the behavior IDs generated by MapConversionService.TransformBehaviorId().
/// Creates simplified behavior categories (wander, stationary, walk, etc.) rather than one-per-movement-type.
/// </summary>
public class BehaviorExtractor
{
    private readonly string _inputPath;
    private readonly string _outputPath;
    private readonly bool _verbose;

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull
    };

    /// <summary>
    /// Core behavior definitions that match the categories used by TransformBehaviorId().
    /// Parameters match what BuildBehaviorParameters() actually generates from map data.
    /// </summary>
    private static readonly List<BehaviorInfo> CoreBehaviors = new()
    {
        // Wander - uses rangeX/rangeY from map data
        new("wander", "Wander", "NPC wanders randomly within a defined range",
            new[] { ("rangeX", "int", (object)0, "Horizontal wander range in tiles"), ("rangeY", "int", (object)0, "Vertical wander range in tiles") }),

        // Stationary - no parameters extracted from map data
        new("stationary", "Stationary", "NPC stays in place, may look around or change facing direction", null),

        // Walk - uses rangeX/rangeY from map data
        new("walk", "Walk", "NPC walks in a pattern or direction",
            new[] { ("rangeX", "int", (object)0, "Horizontal walk range"), ("rangeY", "int", (object)0, "Vertical walk range") }),

        // Jog - no parameters extracted from map data
        new("jog", "Jog", "NPC jogs or runs in place or pattern", null),

        // Follow - no parameters extracted from map data
        new("follow", "Follow", "NPC follows the player or copies player movement", null),

        // Patrol - uses waypoints array from walk_sequence_* movement types
        new("patrol", "Patrol", "NPC follows a defined patrol route with waypoints",
            new[] { ("waypoints", "array", (object)new object[0], "Array of waypoint positions [{x, y}, ...]") }),

        new("invisible", "Invisible", "NPC is invisible and does not interact", null),

        new("buried", "Buried", "NPC is hidden underground (e.g., Diglett encounters)", null),

        new("disguise_tree", "Disguise (Tree)", "NPC disguised as a tree (e.g., Sudowoodo)", null),

        new("disguise_rock", "Disguise (Rock)", "NPC disguised as a rock or mountain (e.g., Kecleon)", null),
    };

    public BehaviorExtractor(string inputPath, string outputPath, bool verbose = false)
    {
        _inputPath = inputPath;
        _outputPath = outputPath;
        _verbose = verbose;
    }

    public (int Behaviors, int Scripts) ExtractAll()
    {
        var behaviorsPath = Path.Combine(_outputPath, "Definitions", "Behaviors");
        var scriptsPath = Path.Combine(_outputPath, "Definitions", "Scripts", "Behaviors");

        Directory.CreateDirectory(behaviorsPath);
        Directory.CreateDirectory(scriptsPath);

        int behaviorCount = 0;
        int scriptCount = 0;

        // Generate behavior and script definitions for each core behavior
        foreach (var behavior in CoreBehaviors)
        {
            // Generate script definition
            var scriptDef = CreateScriptDefinition(behavior);
            var scriptFileName = $"{behavior.Id}.json";
            var scriptFilePath = Path.Combine(scriptsPath, scriptFileName);

            File.WriteAllText(scriptFilePath, JsonSerializer.Serialize(scriptDef, JsonOptions));
            scriptCount++;

            // Generate behavior definition
            var behaviorDef = CreateBehaviorDefinition(behavior);
            var behaviorFileName = $"{behavior.Id}.json";
            var behaviorFilePath = Path.Combine(behaviorsPath, behaviorFileName);

            File.WriteAllText(behaviorFilePath, JsonSerializer.Serialize(behaviorDef, JsonOptions));
            behaviorCount++;

            if (_verbose)
            {
                Console.WriteLine($"  Created behavior: {behavior.Name}");
            }
        }

        return (behaviorCount, scriptCount);
    }

    private object CreateScriptDefinition(BehaviorInfo behavior)
    {
        var parameters = new List<object>();

        if (behavior.Parameters != null)
        {
            foreach (var (name, type, defaultValue, desc) in behavior.Parameters)
            {
                parameters.Add(new Dictionary<string, object>
                {
                    ["name"] = name,
                    ["type"] = type,
                    ["defaultValue"] = defaultValue,
                    ["description"] = desc
                });
            }
        }

        return new Dictionary<string, object>
        {
            ["id"] = $"{IdTransformer.Namespace}:script:behavior/{behavior.Id}",
            ["name"] = $"{behavior.Name} Behavior Script",
            ["description"] = behavior.Description,
            ["scriptPath"] = $"Scripts/Behaviors/{behavior.Id}.csx",
            ["category"] = "behavior",
            ["priority"] = 500,
            ["parameters"] = parameters
        };
    }

    private object CreateBehaviorDefinition(BehaviorInfo behavior)
    {
        var parameters = new List<object>();

        if (behavior.Parameters != null)
        {
            foreach (var (name, type, defaultValue, desc) in behavior.Parameters)
            {
                parameters.Add(new Dictionary<string, object>
                {
                    ["name"] = name,
                    ["type"] = type,
                    ["defaultValue"] = defaultValue,
                    ["description"] = desc
                });
            }
        }

        var result = new Dictionary<string, object>
        {
            ["id"] = $"{IdTransformer.Namespace}:behavior:{behavior.Id}",
            ["name"] = $"{behavior.Name} Behavior",
            ["description"] = behavior.Description,
            ["scriptId"] = $"{IdTransformer.Namespace}:script:behavior/{behavior.Id}",
            ["category"] = behavior.Id
        };

        // Only include parameters if there are any
        if (parameters.Count > 0)
        {
            result["parameters"] = parameters;
        }

        result["parameterOverrides"] = new Dictionary<string, object>();

        return result;
    }

    private record BehaviorInfo(
        string Id,
        string Name,
        string Description,
        (string Name, string Type, object Default, string Description)[]? Parameters
    );
}
